### ISSUE TITLE
Why do we need fixed string format of (some) protocol messages?

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-api#212]
## Context
Some types of the messages declare string format. Example: `refs` package.

## Question
Do we really need to declare fixed string format? Can it be application-specific? Currently strings aren't transmitted in other messages, and unused in smart contracts.

**Comment by alexvanin** [comment]
As far as I remember, we discussed string formats because of extended ACL filter types. There is a [set](https://github.com/nspcc-dev/neofs-api/blob/431335054c3bd2fcff52226e04175b443bcb8a1e/acl/types.proto#L109-L126) of well-known filter keys, such as `$Object:ownerID` or `$Object:version`. Filter value, on the other hand, is a string, so we need to have description of string representation for those types.
