### ISSUE TITLE
Add withdraw/transfer operations

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-api#52]
Previously it was possible to manage internal NeoFS Account directly using NeoFS API. It's currently possible by calling NEP-5 internal balance Smart Contract, but in theory, not all users can do it.

Maybe it would be beneficial to add simple Account operations without direct Neo Blockchain interaction, helping to improve user experience.

**Comment by alexvanin** [comment]
We've decided to implement only `withdaw` method in `accounting` service of API.

Transferring assets of internal banking is not common use case for NeoFS network. However it is still possible, because balance contract is NEP-17 compatible. So any wallet with NEP-17 support can do the job when connected to side chain.

In contrary, withdrawing assets is a common use case. Right now the only way to withdraw is to call NeoFS contract from main net. However it requires some GAS to invoke this method. Instead we can use side chain notification to start withdraw procedure in inner ring nodes. It will cost nothing for the user and every storage node will be able to do that. 

We'll need a method in balance contract that can verify withdraw origin (storage node is a mediator in the scheme). Based on the format of _proof_ API should provide such method to clients.

**Comment by alexvanin** [comment]
> Based on the format of proof API should provide such method to clients.

After internal discussion with @cthulhu-rider and @realloc we've decided that proof should contain combination of sidechain magic number and epoch number as a nonce. Right now there is no API methods to get these numbers and it blocks implementation. However as soon as it will be implemented, we will return to this enhancement.

**Comment by alexvanin** [comment]
Withdraw operation requires to use main chain GAS. Thus user should pay fee to alphabet nodes (https://github.com/nspcc-dev/neofs-contract/issues/70). Withdraw operations from side chain do not fit for this economy model.
