### ISSUE TITLE
Leave only root object related fields for ACL filter

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#85]
ACL filter defines these keys to filter objects (outside of user-defiend headers):
- version
- container ID
- owner ID
- creation epoch
- payload length
- payload hash
- object type
- homomorphic hash

It mostly copies object search filters, however not all of them are quite applicable for ACL tables. Say there is no point to make ACL rules based on hashes or object type (ACL rules seems legit for regular objects only). Maybe we should short this list?

**Comment by realloc** [comment]
I suggest to add clarification to api definition and spec, that eACL works with all object types.

For the list of key to filter I suggest to remove `$Object:containerID`, because requests are already limited to container scope and NeoFS doesn't support cross-container operations. All other fields seem to have valid possible use cases.

What do you think, @alexvanin @cthulhu-rider?

**Comment by realloc** [comment]
To maintain backward compatibility, let's keep things as they are.
